### ISSUE TITLE
Why not reuse existing repo?

### ISSUE THREAD

**Issue by nickw444** [csesoc/csesoc.unsw.edu.au#1]
The existing repo has a lot of existing useful history and context behind it. It would be a shame to lose all of that if we rebuilt the project here. 

What do you think about developing a new website in the old repo on a feature branch until it is ready?

**Comment by gawdn** [comment]
That is an excellent point @nickw444 but doesn't really make sense for this project. Since this project will use a different architectural base, it would essentially nuke that repo anyway and this way it will keep the git branches/history clean. 

You do bring up a good point of ensuring we're ensuring we're (and future devs) are aware of historical context/developer choices - which will we do by linking back to the original repo + adding docs around that. 

Do you think that's reasonable?

**Comment by nickw444** [comment]
Sounds reasonable to me 👍
